"""Initial migration

Revision ID: 92a16077d9e3
Revises: 
Create Date: 2026-07-31 18:21:34.706101

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92a16077d9e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Create the ENUM type first (outside batch context)
    user_roles_enum = postgresql.ENUM(
        'student',
        'admin',
        'mess_manager',
        'hostel_manager',
        name='user_roles',
        create_type=False
    )
    user_roles_enum.create(op.get_bind(), checkfirst=True)
    
    # Step 2: Drop old table if exists
    op.execute("DROP TABLE IF EXISTS complaints CASCADE")
    
    # Step 3: Alter users table WITHOUT batch operations (PostgreSQL doesn't need batch)
    # Add new columns
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_picture_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    
    # Update google_id to not null (set defaults first if needed)
    op.execute("UPDATE users SET google_id = 'unknown_' || id::text WHERE google_id IS NULL")
    op.alter_column('users', 'google_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    
    # Alter email length
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=False)
    
    # Step 4: Convert role column from VARCHAR to ENUM
    # First, ensure all existing roles are valid
    op.execute("""
        UPDATE users 
        SET role = 'student' 
        WHERE role NOT IN ('student', 'admin', 'mess_manager', 'hostel_manager')
    """)
    
    # Update name column with existing data if available
    op.execute("""
        UPDATE users 
        SET name = COALESCE(full_name, email) 
        WHERE name IS NULL
    """)
    op.alter_column('users', 'name', nullable=False)
    
    # Cast role column to ENUM using ALTER TYPE
    op.execute("""
        ALTER TABLE users 
        ALTER COLUMN role TYPE user_roles 
        USING role::text::user_roles
    """)
    
    # Step 5: Update constraints
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    
    # Step 6: Drop old constraints and create new indexes
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_google_id_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    
    # Step 7: Drop old columns
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'profile_image')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Add back old columns
    op.add_column('users', sa.Column('profile_image', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    
    # Update full_name from name before dropping
    op.execute("UPDATE users SET full_name = name")
    op.alter_column('users', 'full_name', nullable=False)
    
    # Step 2: Drop indexes
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    
    # Step 3: Recreate old unique constraints
    op.create_unique_constraint('users_google_id_key', 'users', ['google_id'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    
    # Step 4: Alter columns back
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    
    # Step 5: Convert ENUM back to VARCHAR
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE VARCHAR(30) USING role::text")
    
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    
    op.alter_column('users', 'google_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    
    # Step 6: Drop new columns
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'name')
    
    # Step 7: Recreate old complaints table
    op.create_table('complaints',
        sa.Column('complaint_id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('complaint_id', name='complaints_pkey')
    )
    
    # Step 8: Drop the ENUM type
    user_roles_enum = postgresql.ENUM(
        'student',
        'admin',
        'mess_manager',
        'hostel_manager',
        name='user_roles',
        create_type=False
    )
    user_roles_enum.drop(op.get_bind(), checkfirst=True)
    
    # ### end Alembic commands ###
